name: Unit Tests (UBSAN)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential cmake ninja-build

          sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main"
          sudo add-apt-repository "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main"
          sudo apt-get update

          sudo apt-get install -y clang-19 clang++-19
          sudo apt-get install -y llvm-19 libmlir-19-dev mlir-19-tools

          pip install lit

      - name: Build and test
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_C_COMPILER=clang-19 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_BUILD_TYPE=Debug -DUSE_SANITIZER=undefined -DMLIR_DIR=/usr/lib/llvm-19/lib/cmake/mlir/ -DLLVM_EXTERNAL_LIT=/opt/hostedtoolcache/Python/3.10.18/x64/bin/lit ..
          ninja -j$(nproc)

          cmake --build . --target check-sdfg-opt
